const { Pool } = require("pg");

if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL must be set.");
}

const isProduction =
    process.env.NODE_ENV === "production";


const pool = new Pool({
    connectionString:
        process.env.DATABASE_URL,

    ssl: isProduction
        ? {
              rejectUnauthorized: false
          }
        : false
});


pool.on("error", error => {
    console.error(
        "unexpected postgres pool error:",
        error
    );
});


function convertQuery(query) {
    let parameter = 0;

    return query.replace(
        /\?/g,
        () => {
            parameter += 1;

            return `$${parameter}`;
        }
    );
}


function prepare(query) {
    const sql =
        convertQuery(query);

    return {

        async get(...params) {

            const result =
                await pool.query(
                    sql,
                    params
                );

            return (
                result.rows[0] ||
                undefined
            );
        },


        async all(...params) {

            const result =
                await pool.query(
                    sql,
                    params
                );

            return result.rows;
        },


        async run(...params) {

            const result =
                await pool.query(
                    sql,
                    params
                );

            return {
                changes:
                    result.rowCount,

                lastInsertRowid:
                    result.rows[0]?.id ||
                    null
            };
        }

    };
}


async function initializeDatabase() {

    /*
     * users
     */

    await pool.query(`
        create table if not exists users (

            id integer
                generated by default as identity
                primary key,

            username varchar(30)
                not null
                unique,

            password text
                not null,

            display_name varchar(40)
                not null
                default '',

            bio varchar(500)
                not null
                default '',

            profile_image_url text,

            created_at timestamptz
                not null
                default current_timestamp

        );
    `);


    /*
     * safely add profile image
     * to older databases
     */

    await pool.query(`
        alter table users
        add column if not exists
        display_name varchar(40)
        not null
        default '';
    `);


    await pool.query(`
        alter table users
        add column if not exists
        bio varchar(500)
        not null
        default '';
    `);


    await pool.query(`
        alter table users
        add column if not exists
        profile_image_url text;
    `);


    /*
     * communities
     */

    await pool.query(`
        create table if not exists communities (

            id integer
                generated by default as identity
                primary key,

            name varchar(50)
                not null
                unique,

            description varchar(300)
                not null
                default '',

            created_at timestamptz
                not null
                default current_timestamp

        );
    `);


    /*
     * posts
     */

    await pool.query(`
        create table if not exists posts (

            id integer
                generated by default as identity
                primary key,

            user_id integer
                not null
                references users(id)
                on delete cascade,

            community_id integer
                references communities(id)
                on delete set null,

            content varchar(500)
                not null,

            attachment_url text,

            attachment_name varchar(255),

            created_at timestamptz
                not null
                default current_timestamp

        );
    `);


    /*
     * safely add post attachments
     * to existing databases
     */

    await pool.query(`
        alter table posts
        add column if not exists
        community_id integer
        references communities(id)
        on delete set null;
    `);


    await pool.query(`
        alter table posts
        add column if not exists
        attachment_url text;
    `);


    await pool.query(`
        alter table posts
        add column if not exists
        attachment_name varchar(255);
    `);


    /*
     * comments
     */

    await pool.query(`
        create table if not exists comments (

            id integer
                generated by default as identity
                primary key,

            user_id integer
                not null
                references users(id)
                on delete cascade,

            post_id integer
                not null
                references posts(id)
                on delete cascade,

            content varchar(300)
                not null,

            created_at timestamptz
                not null
                default current_timestamp

        );
    `);


    /*
     * likes
     */

    await pool.query(`
        create table if not exists likes (

            id integer
                generated by default as identity
                primary key,

            user_id integer
                not null
                references users(id)
                on delete cascade,

            post_id integer
                not null
                references posts(id)
                on delete cascade,

            created_at timestamptz
                not null
                default current_timestamp,

            unique (
                user_id,
                post_id
            )

        );
    `);


    /*
     * follows
     */

    await pool.query(`
        create table if not exists follows (

            id integer
                generated by default as identity
                primary key,

            follower_id integer
                not null
                references users(id)
                on delete cascade,

            following_id integer
                not null
                references users(id)
                on delete cascade,

            created_at timestamptz
                not null
                default current_timestamp,

            unique (
                follower_id,
                following_id
            )

        );
    `);


    /*
     * sessions
     */

    await pool.query(`
        create table if not exists user_sessions (

            sid varchar
                not null
                primary key,

            sess json
                not null,

            expire timestamp(6)
                not null

        );
    `);


    /*
     * indexes
     */

    await pool.query(`
        create index if not exists
            posts_user_id_idx
        on posts(user_id);
    `);


    await pool.query(`
        create index if not exists
            posts_community_id_idx
        on posts(community_id);
    `);


    await pool.query(`
        create index if not exists
            posts_created_at_idx
        on posts(created_at desc);
    `);


    await pool.query(`
        create index if not exists
            comments_post_id_idx
        on comments(post_id);
    `);


    await pool.query(`
        create index if not exists
            comments_user_id_idx
        on comments(user_id);
    `);


    await pool.query(`
        create index if not exists
            likes_post_id_idx
        on likes(post_id);
    `);


    await pool.query(`
        create index if not exists
            likes_user_id_idx
        on likes(user_id);
    `);


    await pool.query(`
        create index if not exists
            follows_follower_id_idx
        on follows(follower_id);
    `);


    await pool.query(`
        create index if not exists
            follows_following_id_idx
        on follows(following_id);
    `);


    await pool.query(`
        create index if not exists
            follows_following_id_idx
        on follows(following_id);
    `);


    await pool.query(`
        create index if not exists
            user_sessions_expire_idx
        on user_sessions(expire);
    `);


    console.log(
        "postgresql database initialized."
    );
}


const db = {
    pool,
    prepare,
    initializeDatabase
};


module.exports = db;
