const { Pool } = require("pg");

if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL must be set.");
}

const isProduction = process.env.NODE_ENV === "production";

const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: isProduction
        ? {
              rejectUnauthorized: false
          }
        : false
});

pool.on("error", error => {
    console.error("unexpected postgres pool error:", error);
});

function convertQuery(query) {
    let parameter = 0;

    return query.replace(/\?/g, () => {
        parameter += 1;
        return `$${parameter}`;
    });
}

function prepare(query) {
    const sql = convertQuery(query);

    return {
        get: async (...params) => {
            const result = await pool.query(sql, params);
            return result.rows[0] || undefined;
        },

        all: async (...params) => {
            const result = await pool.query(sql, params);
            return result.rows;
        },

        run: async (...params) => {
            const result = await pool.query(sql, params);

            return {
                changes: result.rowCount,
                lastInsertRowid: result.rows[0]?.id || null
            };
        }
    };
}

async function initializeDatabase() {
    await pool.query(`
        create table if not exists users (
            id integer generated by default as identity primary key,
            username varchar(30) not null unique,
            password text not null,
            bio text not null default '',
            created_at timestamptz not null default current_timestamp
        );

        create table if not exists posts (
            id integer generated by default as identity primary key,
            user_id integer not null references users(id) on delete cascade,
            content varchar(500) not null,
            created_at timestamptz not null default current_timestamp
        );

        create table if not exists comments (
            id integer generated by default as identity primary key,
            user_id integer not null references users(id) on delete cascade,
            post_id integer not null references posts(id) on delete cascade,
            content varchar(300) not null,
            created_at timestamptz not null default current_timestamp
        );

        create table if not exists likes (
            id integer generated by default as identity primary key,
            user_id integer not null references users(id) on delete cascade,
            post_id integer not null references posts(id) on delete cascade,
            created_at timestamptz not null default current_timestamp,
            unique(user_id, post_id)
        );

        create table if not exists follows (
            id integer generated by default as identity primary key,
            follower_id integer not null references users(id) on delete cascade,
            following_id integer not null references users(id) on delete cascade,
            created_at timestamptz not null default current_timestamp,
            unique(follower_id, following_id)
        );

        create table if not exists communities (
            id integer generated by default as identity primary key,
            name varchar(50) not null unique,
            description varchar(300) not null default '',
            created_at timestamptz not null default current_timestamp
        );

        create index if not exists posts_user_id_idx
            on posts(user_id);

        create index if not exists posts_created_at_idx
            on posts(created_at desc);

        create index if not exists comments_post_id_idx
            on comments(post_id);

        create index if not exists comments_user_id_idx
            on comments(user_id);

        create index if not exists likes_post_id_idx
            on likes(post_id);

        create index if not exists likes_user_id_idx
            on likes(user_id);

        create index if not exists follows_follower_id_idx
            on follows(follower_id);

        create index if not exists follows_following_id_idx
            on follows(following_id);

        create index if not exists communities_created_at_idx
            on communities(created_at desc);
    `);

    console.log("postgresql database initialized.");
}

const db = {
    prepare,
    pool,
    initializeDatabase
};

module.exports = db;

initializeDatabase().catch(error => {
    console.error("database initialization failed:");
    console.error(error);
    process.exit(1);
});
