require("dotenv").config();

const express = require("express");
const session = require("express-session");
const bcrypt = require("bcrypt");
const path = require("path");
const db = require("./database");

const app = express();

const port = Number(process.env.PORT) || 3000;
const isProduction = process.env.NODE_ENV === "production";

const adminPath = String(
    process.env.ADMIN_PATH || "vtxadminpanelqz"
).replace(/^\/+|\/+$/g, "");

const adminPassword =
    process.env.ADMIN_PASSWORD || "SamanthaVT*374-SJpa";

if (
    isProduction &&
    (!process.env.SESSION_SECRET ||
        process.env.SESSION_SECRET.length < 32)
) {
    throw new Error(
        "SESSION_SECRET must be set to a long random value in production."
    );
}

app.set("view engine", "ejs");
app.set("trust proxy", 1);

app.use(
    express.urlencoded({
        extended: false,
        limit: "20kb"
    })
);

app.use(
    session({
        secret:
            process.env.SESSION_SECRET ||
            "local-development-secret-change-me",

        resave: false,

        saveUninitialized: false,

        rolling: true,

        cookie: {
            httpOnly: true,
            sameSite: "lax",
            secure: isProduction,
            maxAge: 1000 * 60 * 60 * 24 * 30
        }
    })
);

app.use(
    express.static(path.join(__dirname, "public"), {
        maxAge: isProduction ? "7d" : 0
    })
);

app.locals.formatDate = date => {
    return new Date(date).toLocaleString().toLowerCase();
};

function requireLogin(req, res, next) {
    if (!req.session.userId) {
        return res.redirect("/login");
    }

    next();
}

function requireAdmin(req, res, next) {
    if (!req.session.adminAuthenticated) {
        return res.redirect("/" + adminPath);
    }

    next();
}

async function currentUser(req) {
    if (!req.session.userId) {
        return null;
    }

    return await db.prepare(`
        select
            id,
            username,
            bio,
            created_at
        from users
        where id = ?
    `).get(req.session.userId);
}

async function initializeExtraTables() {
    await db.pool.query(`
        create table if not exists communities (
            id integer generated by default as identity primary key,
            name varchar(50) not null unique,
            description varchar(300) not null default '',
            created_by integer references users(id) on delete set null,
            created_at timestamptz not null default current_timestamp
        );

        create table if not exists community_members (
            id integer generated by default as identity primary key,
            community_id integer not null references communities(id) on delete cascade,
            user_id integer not null references users(id) on delete cascade,
            created_at timestamptz not null default current_timestamp,
            unique(community_id, user_id)
        );

        create index if not exists communities_created_at_idx
            on communities(created_at desc);

        create index if not exists community_members_community_idx
            on community_members(community_id);

        create index if not exists community_members_user_idx
            on community_members(user_id);
    `);

    console.log("extra database tables initialized.");
}

/* -------------------- health -------------------- */

app.get("/health", async (req, res) => {
    try {
        await db.pool.query("select 1");

        res.status(200).json({
            status: "ok",
            service: "helloworld",
            database: "ok"
        });
    } catch (error) {
        console.error("health check error:", error);

        res.status(500).json({
            status: "error",
            service: "helloworld",
            database: "error"
        });
    }
});

/* -------------------- home -------------------- */

app.get("/", (req, res) => {
    if (req.session.userId) {
        return res.redirect("/feed");
    }

    res.render("index");
});

/* -------------------- register -------------------- */

app.get("/register", (req, res) => {
    if (req.session.userId) {
        return res.redirect("/feed");
    }

    res.render("register", {
        error: null
    });
});

app.post("/register", async (req, res) => {
    try {
        const username = String(
            req.body.username || ""
        ).trim().toLowerCase();

        const password = String(
            req.body.password || ""
        );

        if (!/^[a-z0-9_]{3,30}$/.test(username)) {
            return res.render("register", {
                error:
                    "usernames can only use lowercase letters, numbers, and underscores."
            });
        }

        if (password.length < 8) {
            return res.render("register", {
                error:
                    "your password needs at least 8 characters."
            });
        }

        const existing = await db.prepare(
            "select id from users where username = ?"
        ).get(username);

        if (existing) {
            return res.render("register", {
                error: "that username is already taken."
            });
        }

        const hash = await bcrypt.hash(password, 12);

        const result = await db.prepare(`
            insert into users
                (username, password)
            values
                (?, ?)
            returning id
        `).get(username, hash);

        req.session.regenerate(error => {
            if (error) {
                console.error(error);
                return res
                    .status(500)
                    .send("something went wrong.");
            }

            req.session.userId = result.id;

            req.session.save(saveError => {
                if (saveError) {
                    console.error(saveError);

                    return res
                        .status(500)
                        .send("something went wrong.");
                }

                res.redirect("/feed");
            });
        });
    } catch (error) {
        console.error("register error:", error);

        res.status(500).send("something went wrong.");
    }
});

/* -------------------- login -------------------- */

app.get("/login", (req, res) => {
    if (req.session.userId) {
        return res.redirect("/feed");
    }

    res.render("login", {
        error: null
    });
});

app.post("/login", async (req, res) => {
    try {
        const username = String(
            req.body.username || ""
        ).trim().toLowerCase();

        const password = String(
            req.body.password || ""
        );

        const user = await db.prepare(
            "select * from users where username = ?"
        ).get(username);

        if (!user) {
            return res.render("login", {
                error: "we couldn't find that account."
            });
        }

        const valid = await bcrypt.compare(
            password,
            user.password
        );

        if (!valid) {
            return res.render("login", {
                error: "that password isn't correct."
            });
        }

        req.session.regenerate(error => {
            if (error) {
                console.error(error);

                return res
                    .status(500)
                    .send("something went wrong.");
            }

            req.session.userId = user.id;

            req.session.save(saveError => {
                if (saveError) {
                    console.error(saveError);

                    return res
                        .status(500)
                        .send("something went wrong.");
                }

                res.redirect("/feed");
            });
        });
    } catch (error) {
        console.error("login error:", error);

        res.status(500).send(
            "something went wrong while logging you in."
        );
    }
});

/* -------------------- logout -------------------- */

app.post("/logout", requireLogin, (req, res) => {
    req.session.destroy(error => {
        if (error) {
            console.error(error);
        }

        res.clearCookie("connect.sid");
        res.redirect("/");
    });
});

/* -------------------- feed -------------------- */

app.get("/feed", requireLogin, async (req, res) => {
    try {
        const user = await currentUser(req);

        if (!user) {
            return res.redirect("/login");
        }

        const posts = await db.prepare(`
            select
                posts.*,
                users.username,

                (
                    select count(*)
                    from likes
                    where likes.post_id = posts.id
                ) as likes,

                (
                    select count(*)
                    from comments
                    where comments.post_id = posts.id
                ) as comments,

                exists (
                    select 1
                    from likes
                    where likes.post_id = posts.id
                    and likes.user_id = ?
                ) as liked

            from posts

            join users
                on users.id = posts.user_id

            order by posts.created_at desc

            limit 100
        `).all(user.id);

        const getComments = db.prepare(`
            select
                comments.id,
                comments.content,
                comments.created_at,
                users.username

            from comments

            join users
                on users.id = comments.user_id

            where comments.post_id = ?

            order by comments.created_at asc
        `);

        for (const post of posts) {
            post.comment_list =
                await getComments.all(post.id);
        }

        const communities = await db.prepare(`
            select
                communities.*,
                users.username as creator,

                (
                    select count(*)
                    from community_members
                    where community_members.community_id =
                        communities.id
                ) as members

            from communities

            left join users
                on users.id = communities.created_by

            order by communities.created_at desc
        `).all();

        res.render("feed", {
            user,
            posts,
            communities
        });
    } catch (error) {
        console.error("feed error:", error);

        res.status(500).send("internal server error.");
    }
});

/* -------------------- create post -------------------- */

app.post("/posts", requireLogin, async (req, res) => {
    try {
        const content = String(
            req.body.content || ""
        ).trim();

        if (!content || content.length > 500) {
            return res.redirect("/feed");
        }

        await db.prepare(`
            insert into posts
                (user_id, content)
            values
                (?, ?)
        `).run(
            req.session.userId,
            content
        );

        res.redirect("/feed");
    } catch (error) {
        console.error("create post error:", error);

        res.status(500).send("internal server error.");
    }
});

/* -------------------- delete own post -------------------- */

app.post(
    "/posts/:id/delete",
    requireLogin,
    async (req, res) => {
        try {
            const postId = Number(req.params.id);

            if (!Number.isInteger(postId)) {
                return res.redirect("/feed");
            }

            await db.prepare(`
                delete from posts
                where id = ?
                and user_id = ?
            `).run(
                postId,
                req.session.userId
            );

            res.redirect(req.get("referer") || "/feed");
        } catch (error) {
            console.error("delete post error:", error);

            res.status(500).send(
                "could not delete post."
            );
        }
    }
);

/* -------------------- like -------------------- */

app.post(
    "/posts/:id/like",
    requireLogin,
    async (req, res) => {
        try {
            const postId = Number(req.params.id);

            if (!Number.isInteger(postId)) {
                return res.redirect("/feed");
            }

            const existing = await db.prepare(`
                select id
                from likes
                where user_id = ?
                and post_id = ?
            `).get(
                req.session.userId,
                postId
            );

            if (existing) {
                await db.prepare(
                    "delete from likes where id = ?"
                ).run(existing.id);
            } else {
                await db.prepare(`
                    insert into likes
                        (user_id, post_id)
                    values
                        (?, ?)
                    on conflict (user_id, post_id)
                    do nothing
                `).run(
                    req.session.userId,
                    postId
                );
            }

            res.redirect(req.get("referer") || "/feed");
        } catch (error) {
            console.error("like error:", error);

            res.status(500).send(
                "could not update like."
            );
        }
    }
);

/* -------------------- comments page -------------------- */

app.get(
    "/posts/:id/comments",
    requireLogin,
    async (req, res) => {
        try {
            const postId = Number(req.params.id);

            if (!Number.isInteger(postId)) {
                return res.status(404).send(
                    "post not found."
                );
            }

            const post = await db.prepare(`
                select
                    posts.*,
                    users.username,

                    (
                        select count(*)
                        from likes
                        where likes.post_id = posts.id
                    ) as likes

                from posts

                join users
                    on users.id = posts.user_id

                where posts.id = ?
            `).get(postId);

            if (!post) {
                return res.status(404).send(
                    "post not found."
                );
            }

            const comments = await db.prepare(`
                select
                    comments.id,
                    comments.content,
                    comments.created_at,
                    users.username

                from comments

                join users
                    on users.id = comments.user_id

                where comments.post_id = ?

                order by comments.created_at asc
            `).all(postId);

            const user = await currentUser(req);

            res.render("comments", {
                user,
                post,
                comments
            });
        } catch (error) {
            console.error(
                "comments page error:",
                error
            );

            res.status(500).send(
                "internal server error."
            );
        }
    }
);

/* -------------------- create comment -------------------- */

app.post(
    "/posts/:id/comments",
    requireLogin,
    async (req, res) => {
        try {
            const postId = Number(req.params.id);

            const content = String(
                req.body.content || ""
            ).trim();

            if (
                !Number.isInteger(postId) ||
                !content ||
                content.length > 300
            ) {
                return res.redirect(
                    `/posts/${postId}/comments`
                );
            }

            const post = await db.prepare(
                "select id from posts where id = ?"
            ).get(postId);

            if (!post) {
                return res.status(404).send(
                    "post not found."
                );
            }

            await db.prepare(`
                insert into comments
                    (user_id, post_id, content)
                values
                    (?, ?, ?)
            `).run(
                req.session.userId,
                postId,
                content
            );

            res.redirect(
                `/posts/${postId}/comments`
            );
        } catch (error) {
            console.error(
                "comment error:",
                error
            );

            res.status(500).send(
                "internal server error."
            );
        }
    }
);

/* -------------------- profile -------------------- */

app.get(
    "/u/:username",
    requireLogin,
    async (req, res) => {
        try {
            const username = String(
                req.params.username
            ).toLowerCase();

            const user = await db.prepare(`
                select
                    id,
                    username,
                    bio,
                    created_at
                from users
                where username = ?
            `).get(username);

            if (!user) {
                return res.status(404).send(
                    "user not found."
                );
            }

            const posts = await db.prepare(`
                select
                    posts.*,

                    (
                        select count(*)
                        from likes
                        where likes.post_id = posts.id
                    ) as likes,

                    (
                        select count(*)
                        from comments
                        where comments.post_id = posts.id
                    ) as comments

                from posts

                where posts.user_id = ?

                order by posts.created_at desc
            `).all(user.id);

            const followers = await db.prepare(`
                select count(*) as count
                from follows
                where following_id = ?
            `).get(user.id);

            const following = await db.prepare(`
                select count(*) as count
                from follows
                where follower_id = ?
            `).get(user.id);

            const isFollowing =
                user.id !== req.session.userId &&
                !!(
                    await db.prepare(`
                        select id
                        from follows
                        where follower_id = ?
                        and following_id = ?
                    `).get(
                        req.session.userId,
                        user.id
                    )
                );

            const profileUser =
                await currentUser(req);

            res.render("profile", {
                user,
                posts,
                followers: followers.count,
                following: following.count,
                isFollowing,
                currentUser: profileUser
            });
        } catch (error) {
            console.error(
                "profile error:",
                error
            );

            res.status(500).send(
                "internal server error."
            );
        }
    }
);

/* -------------------- profile customization -------------------- */

app.post(
    "/profile/edit",
    requireLogin,
    async (req, res) => {
        try {
            const bio = String(
                req.body.bio || ""
            ).trim().slice(0, 500);

            await db.prepare(`
                update users
                set bio = ?
                where id = ?
            `).run(
                bio,
                req.session.userId
            );

            res.redirect(
                req.get("referer") || "/feed"
            );
        } catch (error) {
            console.error(
                "profile update error:",
                error
            );

            res.status(500).send(
                "could not update profile."
            );
        }
    }
);

/* -------------------- follow -------------------- */

app.post(
    "/u/:username/follow",
    requireLogin,
    async (req, res) => {
        try {
            const username = String(
                req.params.username
            ).toLowerCase();

            const target = await db.prepare(
                "select id from users where username = ?"
            ).get(username);

            if (
                !target ||
                target.id === req.session.userId
            ) {
                return res.redirect(
                    "/u/" + username
                );
            }

            const existing = await db.prepare(`
                select id
                from follows
                where follower_id = ?
                and following_id = ?
            `).get(
                req.session.userId,
                target.id
            );

            if (existing) {
                await db.prepare(
                    "delete from follows where id = ?"
                ).run(existing.id);
            } else {
                await db.prepare(`
                    insert into follows
                        (follower_id, following_id)
                    values
                        (?, ?)
                    on conflict
                        (follower_id, following_id)
                    do nothing
                `).run(
                    req.session.userId,
                    target.id
                );
            }

            res.redirect(
                "/u/" + username
            );
        } catch (error) {
            console.error(
                "follow error:",
                error
            );

            res.status(500).send(
                "could not update follow."
            );
        }
    }
);

/* =========================================================
   communities
   ========================================================= */

/* -------------------- community list -------------------- */

app.get(
    "/communities",
    requireLogin,
    async (req, res) => {
        try {
            const user = await currentUser(req);

            const communities = await db.prepare(`
                select
                    communities.*,
                    users.username as creator,

                    (
                        select count(*)
                        from community_members
                        where community_members.community_id =
                            communities.id
                    ) as members

                from communities

                left join users
                    on users.id = communities.created_by

                order by communities.created_at desc
            `).all();

            res.render("communities", {
                user,
                communities
            });
        } catch (error) {
            console.error(
                "communities error:",
                error
            );

            res.status(500).send(
                "internal server error."
            );
        }
    }
);

/* -------------------- community page -------------------- */

app.get(
    "/communities/:id",
    requireLogin,
    async (req, res) => {
        try {
            const communityId = Number(
                req.params.id
            );

            if (!Number.isInteger(communityId)) {
                return res.status(404).send(
                    "community not found."
                );
            }

            const community = await db.prepare(`
                select
                    communities.*,
                    users.username as creator,

                    (
                        select count(*)
                        from community_members
                        where community_members.community_id =
                            communities.id
                    ) as members

                from communities

                left join users
                    on users.id = communities.created_by

                where communities.id = ?
            `).get(communityId);

            if (!community) {
                return res.status(404).send(
                    "community not found."
                );
            }

            res.render("community", {
                user: await currentUser(req),
                community
            });
        } catch (error) {
            console.error(
                "community page error:",
                error
            );

            res.status(500).send(
                "internal server error."
            );
        }
    }
);

/* -------------------- join community -------------------- */

app.post(
    "/communities/:id/join",
    requireLogin,
    async (req, res) => {
        try {
            const communityId = Number(
                req.params.id
            );

            if (!Number.isInteger(communityId)) {
                return res.redirect(
                    "/communities"
                );
            }

            const community = await db.prepare(
                "select id from communities where id = ?"
            ).get(communityId);

            if (!community) {
                return res.status(404).send(
                    "community not found."
                );
            }

            await db.prepare(`
                insert into community_members
                    (community_id, user_id)
                values
                    (?, ?)
                on conflict
                    (community_id, user_id)
                do nothing
            `).run(
                communityId,
                req.session.userId
            );

            res.redirect(
                `/communities/${communityId}`
            );
        } catch (error) {
            console.error(
                "join community error:",
                error
            );

            res.status(500).send(
                "could not join community."
            );
        }
    }
);

/* =========================================================
   admin panel
   ========================================================= */

/*
    admin url:

    /<admin path>

    default:
    /vtxadminpanelqz

    for production, set:

    ADMIN_PATH=your-secret-path
    ADMIN_PASSWORD=your-admin-password
*/

app.get(
    "/" + adminPath,
    (req, res) => {
        if (req.session.adminAuthenticated) {
            return res.redirect(
                "/" + adminPath + "/dashboard"
            );
        }

        res.render("admin-login", {
            error: null
        });
    }
);

app.post(
    "/" + adminPath,
    (req, res) => {
        const password = String(
            req.body.password || ""
        );

        if (password !== adminPassword) {
            return res.status(401).render(
                "admin-login",
                {
                    error: "incorrect password."
                }
            );
        }

        req.session.adminAuthenticated = true;

        req.session.save(error => {
            if (error) {
                console.error(
                    "admin session error:",
                    error
                );

                return res
                    .status(500)
                    .send("something went wrong.");
            }

            res.redirect(
                "/" + adminPath + "/dashboard"
            );
        });
    }
);

/* -------------------- admin dashboard -------------------- */

app.get(
    "/" + adminPath + "/dashboard",
    requireAdmin,
    async (req, res) => {
        try {
            const users = await db.prepare(`
                select
                    id,
                    username,
                    bio,
                    created_at
                from users
                order by created_at desc
                limit 500
            `).all();

            const posts = await db.prepare(`
                select
                    posts.id,
                    posts.content,
                    posts.created_at,
                    users.username

                from posts

                join users
                    on users.id = posts.user_id

                order by posts.created_at desc

                limit 500
            `).all();

            const communities =
                await db.prepare(`
                    select
                        communities.*,
                        users.username as creator

                    from communities

                    left join users
                        on users.id =
                            communities.created_by

                    order by communities.created_at desc
                `).all();

            res.render("admin", {
                users,
                posts,
                communities,
                adminPath
            });
        } catch (error) {
            console.error(
                "admin dashboard error:",
                error
            );

            res.status(500).send(
                "internal server error."
            );
        }
    }
);

/* -------------------- admin logout -------------------- */

app.post(
    "/" + adminPath + "/logout",
    requireAdmin,
    (req, res) => {
        req.session.adminAuthenticated = false;

        req.session.save(() => {
            res.redirect(
                "/" + adminPath
            );
        });
    }
);

/* -------------------- admin delete post -------------------- */

app.post(
    "/" + adminPath + "/posts/:id/delete",
    requireAdmin,
    async (req, res) => {
        try {
            const postId = Number(
                req.params.id
            );

            if (!Number.isInteger(postId)) {
                return res.redirect(
                    "/" + adminPath + "/dashboard"
                );
            }

            await db.prepare(
                "delete from posts where id = ?"
            ).run(postId);

            res.redirect(
                "/" + adminPath + "/dashboard"
            );
        } catch (error) {
            console.error(
                "admin post delete error:",
                error
            );

            res.status(500).send(
                "could not delete post."
            );
        }
    }
);

/* -------------------- admin delete account -------------------- */

app.post(
    "/" + adminPath + "/users/:id/delete",
    requireAdmin,
    async (req, res) => {
        try {
            const userId = Number(
                req.params.id
            );

            if (!Number.isInteger(userId)) {
                return res.redirect(
                    "/" + adminPath + "/dashboard"
                );
            }

            await db.prepare(
                "delete from users where id = ?"
            ).run(userId);

            res.redirect(
                "/" + adminPath + "/dashboard"
            );
        } catch (error) {
            console.error(
                "admin user delete error:",
                error
            );

            res.status(500).send(
                "could not delete account."
            );
        }
    }
);

/* -------------------- admin create community -------------------- */

app.post(
    "/" + adminPath + "/communities/create",
    requireAdmin,
    async (req, res) => {
        try {
            const name = String(
                req.body.name || ""
            ).trim().toLowerCase();

            const description = String(
                req.body.description || ""
            ).trim();

            if (
                !/^[a-z0-9_-]{2,50}$/.test(name)
            ) {
                return res.status(400).send(
                    "community names can only use lowercase letters, numbers, underscores, and hyphens."
                );
            }

            if (description.length > 300) {
                return res.status(400).send(
                    "community description is too long."
                );
            }

            const existing = await db.prepare(
                "select id from communities where name = ?"
            ).get(name);

            if (existing) {
                return res.status(400).send(
                    "that community already exists."
                );
            }

            await db.prepare(`
                insert into communities
                    (name, description, created_by)
                values
                    (?, ?, null)
            `).run(
                name,
                description
            );

            res.redirect(
                "/" + adminPath + "/dashboard"
            );
        } catch (error) {
            console.error(
                "admin community creation error:",
                error
            );

            res.status(500).send(
                "could not create community."
            );
        }
    }
);

/* -------------------- admin delete community -------------------- */

app.post(
    "/" + adminPath + "/communities/:id/delete",
    requireAdmin,
    async (req, res) => {
        try {
            const communityId = Number(
                req.params.id
            );

            if (!Number.isInteger(communityId)) {
                return res.redirect(
                    "/" + adminPath + "/dashboard"
                );
            }

            await db.prepare(
                "delete from communities where id = ?"
            ).run(communityId);

            res.redirect(
                "/" + adminPath + "/dashboard"
            );
        } catch (error) {
            console.error(
                "admin community delete error:",
                error
            );

            res.status(500).send(
                "could not delete community."
            );
        }
    }
);

/* -------------------- 404 -------------------- */

app.use((req, res) => {
    res.status(404).send("page not found.");
});

/* -------------------- startup -------------------- */

async function startServer() {
    try {
        await db.initializeDatabase();
        await initializeExtraTables();

        app.listen(port, () => {
            console.log(
                "helloworld is running on port " + port
            );

            console.log(
                "admin panel: /" + adminPath
            );
        });
    } catch (error) {
        console.error(
            "server startup failed:"
        );

        console.error(error);

        process.exit(1);
    }
}

startServer();
